import { supabase } from "@/integrations/supabase/client";
import { CleanMember } from "./dataTransform";

export async function insertMemberData(transformedData: CleanMember[]) {
  console.log('Starting batch insert of member data');
  
  for (const member of transformedData) {
    try {
      // First, ensure collector exists
      const { data: collector, error: collectorError } = await supabase
        .from('collectors')
        .select('id, prefix, number')
        .eq('name', member.collector)
        .single();

      if (collectorError) {
        console.error('Error finding collector:', collectorError);
        throw new Error(`Collector not found: ${member.collector}`);
      }

      console.log('Found collector:', collector);

      // Insert member with empty member_number (trigger will generate it)
      const { data: memberData, error: memberError } = await supabase
        .from('members')
        .insert({
          collector_id: collector.id,
          full_name: member.full_name,
          address: member.address,
          status: 'active',
          verified: member.verified,
          member_number: '' // Will be generated by trigger
        })
        .select()
        .single();

      if (memberError) {
        console.error('Error inserting member:', memberError);
        throw memberError;
      }

      console.log('Successfully inserted member:', memberData);

      // Insert admin notes if any
      if (member.notes?.length) {
        const { error: notesError } = await supabase
          .from('admin_notes')
          .insert(
            member.notes.map((note: string) => ({
              member_id: memberData.id,
              note: note
            }))
          );

        if (notesError) {
          console.error('Error inserting notes:', notesError);
        }
      }

      console.log(`Successfully processed member: ${member.full_name}`);
    } catch (error) {
      console.error('Error processing member:', error);
      throw error;
    }
  }
}